version: '3.5'
networks:
  vericlear:
    name: vericlear_net
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:5.0.0
    hostname: zookeeper-1
    container_name: zookeeper-1
    networks:
      - vericlear
    ports:
      - '2181:2181'
    env_file:
      - zookeeper.env
    healthcheck:
      test: /bin/sh -c '[ \"imok\" = \"$$(echo ruok | nc -w 1 127.0.0.1 2181)\" ]' || exit 1
      interval: 1m
    volumes:
      - zookeeper-1-data:/var/lib/zookeeper/data/
      - zookeeper-1-log:/var/lib/zookeeper/log/

  kafka-1:
    image: confluentinc/cp-kafka:5.0.0
    hostname: kafka-1
    container_name: kafka-1
    networks:
      - vericlear
    stop_grace_period: 5m
    depends_on:
      - zookeeper-1
    ports:
      - "9092:9092"
      - "29092:29092"
    env_file:
      - kafka.env
    volumes:
      - kafka-1-data:/var/lib/kafka/data/

  kafdrop:
    build: 
      context: ./devBuild
    image: vermicfintech/kafdrop:dev
    restart: "no"
    ports:
      - "9005:9005"
    networks:
      - vericlear
    environment:
      SERVER_SERVLET_CONTEXTPATH: "/"
      KAFKA_BROKERCONNECT: "kafka-1:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka-1"

volumes:
    zookeeper-1-data:
    zookeeper-1-log:
    kafka-1-data:      

